// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aid
{
    internal sealed partial class Vsix
    {
        public const string Id = "Aid.1622b9b4-9149-4824-a914-3b6c0c09aab1";
        public const string Name = "Aid 2022";
        public const string Description = @"提供支持，以方便使用者通过外部程序扩展Visual Studio。";
        public const string Language = "zh-Hans";
        public const string Version = "0.1";
        public const string Author = "liff.engineer@gmail.com";
        public const string Tags = "";
    }
}
