// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AidString = "c2fbb5ce-8365-4363-b7f7-94e93e1f5a93";
        public static Guid Aid = new Guid(AidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AidMenuGroup = 0x0001;
        public const int AidToolbarGroup = 0x0002;
        public const int AidToolbar = 0x0003;
        public const int CommandPaletteCommand = 0x0100;
        public const int CommandPaletteToolBarCommand = 0x0101;
    }
}