// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTScanCodeView
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSTScanCodeView.b2d8fbcc-1f78-46c0-bce9-d5222d1176a5";
        public const string Name = "VSTScanCodeView";
        public const string Description = @"Use TscanCode  in Visual Studio . ";
        public const string Language = "zh-CN";
        public const string Version = "0.1";
        public const string Author = "liff.engineer@gmail.com";
        public const string Tags = "";
    }
}
