// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTScanCodeView
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSTScanCodeViewString = "780e4dc3-872c-4f9d-927d-51f05e5b5d3c";
        public static Guid VSTScanCodeView = new Guid(VSTScanCodeViewString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ViewResultCommand = 0x0100;
        public const int ScanCodeWindowToolbar = 0x1000;
        public const int ScanCodeWindowToolbarGroup = 0x1050;
        public const int ScanCurrentFileCommandButton = 0x0111;
        public const int ScanFolderCommandButton = 0x0112;
        public const int ScanFileAndShowCommandButton = 0x0113;
        public const int ScanFolderAndShowCommandButton = 0x0114;
        public const int ScanCodeWindowMenu = 0x1001;
        public const int ScanCodeWindowMenuGroup = 0x1100;
    }
}