// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aid
{
    internal sealed partial class Vsix
    {
        public const string Id = "Aid.84adc7fd-f303-4ed5-9c98-1c6270d3be7b";
        public const string Name = "Aid 2019";
        public const string Description = @"提供支持，以方便使用者通过外部程序扩展Visual Studio。";
        public const string Language = "zh-Hans";
        public const string Version = "0.1";
        public const string Author = "liff.engineer@gmail.com";
        public const string Tags = "";
    }
}
